services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    env_file:
      - .env.local
    depends_on:
      - db
      - localstack
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-1

volumes:
  postgres_data:
  bundle:
