ARG RUBY_VERSION=3.4.2
FROM docker.io/library/ruby:$RUBY_VERSION

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      curl \
      libpq-dev \
      postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY db-setup-entrypoint.sh /usr/local/bin/db-setup-entrypoint.sh
RUN chmod +x /usr/local/bin/db-setup-entrypoint.sh

ENTRYPOINT ["db-setup-entrypoint.sh"]
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
