module ErrorCodes
  UNAUTHORIZED            = "UNAUTHORIZED"
  NOT_FOUND               = "NOT_FOUND"
  UNPROCESSABLE_ENTITY    = "UNPROCESSABLE_ENTITY"
  BAD_REQUEST             = "BAD_REQUEST"
  ACCOUNT_ALREADY_EXISTS  = "ACCOUNT_ALREADY_EXISTS"
  USERNAME_TAKEN          = "USERNAME_TAKEN"
end
