# APIレスポンスの error.code フィールドで返す文字列定数
module ErrorCodes
  UNAUTHORIZED            = "UNAUTHORIZED"
  NOT_FOUND               = "NOT_FOUND"
  UNPROCESSABLE_ENTITY    = "UNPROCESSABLE_ENTITY"
  BAD_REQUEST             = "BAD_REQUEST"
  ACCOUNT_ALREADY_EXISTS  = "ACCOUNT_ALREADY_EXISTS"
  USERNAME_TAKEN          = "USERNAME_TAKEN"
  VALIDATION_ERROR        = "VALIDATION_ERROR"
  INTERNAL_SERVER_ERROR   = "INTERNAL_SERVER_ERROR"
  EXTERNAL_API_ERROR      = "EXTERNAL_API_ERROR"
  CONFLICT                = "CONFLICT"
end
